### ISSUE TITLE
Miui8 无法调起权限界面

### ISSUE THREAD

**Issue by czy1121** [zhaozepeng/FloatWindowPermission#1]
Miui 8.0.4.0 是 com.miui.permcenter.permissions.AppPermissionsEditorActivity
Miui 8.6.x 是 com.miui.permcenter.permissions.PermissionsEditorActivity
不知道是哪个版本开始改变的

**Comment by zhaozepeng** [comment]
miui8 已经是 6.0 了，所以使用

```
Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION);
    intent.setData(Uri.parse("package:" + getPackageName()));
    startActivityForResult(intent, REQUEST_CODE);
```

应该是可以的，现在是不行么？

**Comment by czy1121** [comment]
呃，好的，我试试
看文跳过那一段了 - -

**Comment by zhaozepeng** [comment]
可以么？我的小米2升级了miui8，我周末试一下

**Comment by czy1121** [comment]
没问题的，是我用错了
当时没使用Settings.ACTION_MANAGE_OVERLAY_PERMISSION
而且 targetSdkVersion 为 22，使用 checkSelfPermission 总是返回0
MiuiUtils.checkFloatWindowPermission 能判断，MiuiUtils.applyMiuiPermission 却调不起授权界面让我有些混乱
现在没问题了

**Comment by zhaozepeng** [comment]
嗯，好的，应该是没问题的，谢谢反馈～
