### ISSUE TITLE
检测悬浮窗是否开启，点击返回按钮时怎么获取这个状态？

### ISSUE THREAD

**Issue by JackyBower** [zhaozepeng/FloatWindowPermission#11]
在service中弹出dialog的时候去检测悬浮窗是否开启，然后点击返回的时候怎么获取这个状态？
场景：一个用户在其它手机登录的时候，service会发一个状态给手机，告知这个用户在其它设备已经登录，但是在弹出窗口的时候悬浮窗没有开启，然后引导用户进行设置，返回的时候这个悬浮窗的状态怎么获取？

**Comment by zhaozepeng** [comment]
我现在的处理方式是第一次用户点击显示没有权限，打开权限之后需要用户再次点击；
用户开启权限成功这个动作现在貌似是没有办法知道的，不过可以这么处理，每一秒轮询去检测悬浮窗权限，检测60s左右（或者其他更长的时间），一检测到用户开启，就弹出权限框；
很多人都有这个用户开启权限监听的动作，貌似这个系统没有提供，只能去做一个轮询了。

**Comment by JackyBower** [comment]
是的，除了轮询去检测这个状态，暂时没有更好的办法了，谢谢
