### ISSUE TITLE
如何让悬浮窗只在应用内显示？？？

### ISSUE THREAD

**Issue by chenkexu** [zhaozepeng/FloatWindowPermission#19]
如何让悬浮窗只在应用内显示？？？回到桌面的时候不显示。

**Comment by BaconLi** [comment]
貌似只能通过获取栈顶的activity来判断了，或者通过service每500ms获取一次栈顶的activity或者通过辅助服务监听桌面内容改变来实现

**Comment by chenkexu** [comment]
@BaconLi 有点难搞啊

**Comment by chenkexu** [comment]
@BaconLi 如何判断应用是否在前台？？

**Comment by BaconLi** [comment]
@chenkexu 是获取栈顶Activity可以看看这个https://github.com/MohammadAdib/LollipopRecentApps

**Comment by BaconLi** [comment]
@chenkexu  5.0以下的直接获取runningTask就行

**Comment by chenkexu** [comment]
@BaconLi    @Override
    public void onTrimMemory(int level) {
        super.onTrimMemory(level);
        if (level == TRIM_MEMORY_UI_HIDDEN) {
            isBackGround = true;
            Log.i("bo", "APP遁入后台");
        }
    }  
application重写的这个方法您见过吗？

**Comment by BaconLi** [comment]
这个是内存不足被回收的时候调用吧，没用过，具体不大清楚

**Comment by zhaozepeng** [comment]
@chenkexu @BaconLi 不用哦，只需要使用 type_application就行了～
