### ISSUE TITLE
vivo 和步步高的手机需要去单独获取权限吗

### ISSUE THREAD

**Issue by willBars** [zhaozepeng/FloatWindowPermission#21]
博主:
  你好,您这个试过在vivo和步步高手机上面需要申请权限的吗?

**Comment by zhaozepeng** [comment]
vivo有几款机型也是需要单独设置的

**Comment by zfl187** [comment]
单独设置，是要怎么处理啊，博主

**Comment by zfl187** [comment]
vivo的几款7.0的手机，有时候能自己显示出来悬浮窗，有时候不能。vivo x9.

**Comment by 743ren** [comment]
应该是 vivo 手机系统有 bug。试了微信的悬浮窗，也是明明悬浮窗能出来了，下次就又提示说需要权限。
发现一种情况，通过开启方法跳转到Android系统本身的那个设置，应用从后台到前台，立刻检查权限，说没有权限，但你延时，比如200ms后再检测，权限就有了。
而且开启了权限，i 管家里的状态还是未开启，明显就是系统做的不好，没把状态同步过来。
