### ISSUE TITLE
360手机F4  不能跳转到权限开启页面 怎么办

### ISSUE THREAD

**Issue by TomorrowDreamer** [zhaozepeng/FloatWindowPermission#22]
can't open permission page with particular name, please use "adb shell dumpsys activity" command and tell me the name of the float window permission page

**Comment by TomorrowDreamer** [comment]
@zhaozepeng   360手机F4找不到悬浮窗权限开启页面，如何得到这个页面？

**Comment by zhaozepeng** [comment]
系统版本多少，应该是在 360 管家里面

**Comment by TomorrowDreamer** [comment]
@zhaozepeng  最后在安全卫士找到了  3ks
