### ISSUE TITLE
oppoR9 版本5.1.1 没适配到，退到home界面悬浮窗是不显示的（此时没悬浮框权限也没检测到没权限）

### ISSUE THREAD

**Issue by LegendKe** [zhaozepeng/FloatWindowPermission#23]

**Comment by LegendKe** [comment]
看你文章有适配oppo R7 ,A37说默认开启的，但如果用户特意去关掉了悬浮窗权限，请问这时显示悬浮框能检查到没有权限吗 ? 因为没权限的话返回home界面会不显示

**Comment by LegendKe** [comment]
已单独适配oppo R9

**Comment by KerryZhang2016** [comment]
@LegendKe 你好，请问如何适配R9的，可以说一下么？

**Comment by zhaozepeng** [comment]
@LegendKe 可以发一个 MR出来么？

**Comment by LegendKe** [comment]
/**
     * 
     * 去oppo R9权限申请页面手机管家com.coloros.safecenter
     */
    public static void applyPermission(Context context) {
        try {
            Intent intent = new Intent();
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            ComponentName comp = new ComponentName("com.coloros.safecenter", "com.coloros.safecenter.sysfloatwindow.FloatWindowListActivity");//悬浮窗管理页面
            intent.setComponent(comp);
            context.startActivity(intent);
        }catch (ActivityNotFoundException e){
            e.printStackTrace();
        } catch(Exception e){
            e.printStackTrace();
        }
    }

**Comment by zhaozepeng** [comment]
@LegendKe @KerryZhang2016 谁把代码写的完整一点，发一个merge request出来哈，麻烦了

**Comment by zhaozepeng** [comment]
@LegendKe @KerryZhang2016 
MR有点乱，我整理了一下，提交：79e47dc3944d48f17c6756d0185c7ee0f72e1bca

**Comment by pinehallnick** [comment]
oppo A33的权限页面路径是下面这个：

public static void applyOppoPermission(Context context) {
       ...
            ComponentName comp = new ComponentName("_**com.color.safecenter**_", "**com.color.safecenter.permission.PermissionManagerActivity**");//悬浮窗管理页面
            ...
        catch(Exception e){
            e.printStackTrace();
        }
    }

**Comment by jinsandazi** [comment]
怎么适配的，有 demo 吗

**Comment by zhaozepeng** [comment]
@jinsandazi 代码已合入，可以看提交记录
