### ISSUE TITLE
有个魅族跳转授权页面失败

### ISSUE THREAD

**Issue by amazingokc** [zhaozepeng/FloatWindowPermission#28]
我看了下你的代码6.0以上系统魅族你没有用通用的跳转方法，而是用了6.0以下的跳转方法，下面是日志：
https://github.com/zhaozepeng/FloatWindowPermission/blob/master/FloatWindowPermission/app/src/main/java/com/android/permission/FloatWindowManager.java

**Comment by zhaozepeng** [comment]
![image](https://user-images.githubusercontent.com/13027320/35793175-79bb30ca-0a8b-11e8-8a43-e33c849db62c.png)
