### ISSUE TITLE
基于安卓7.0的MIUI9适配问题

### ISSUE THREAD

**Issue by WuCh1k1n** [zhaozepeng/FloatWindowPermission#31]
经过测试，在基于安卓6.0的MIUI9上可以正常显示悬浮窗，在基于安卓7.0的MIUI9上却无法显示（即时打开了悬浮窗权限）。请问为什么会这样呢？

**Comment by zhaozepeng** [comment]
小米ROM特殊控制了？你可以看一下其他应用可以展示么？

**Comment by WuCh1k1n** [comment]
是我的安卓系统版本判断有问题，现在问题已经解决了，MIUI9适配正常。非常感谢！
