### ISSUE TITLE
Samsung Galaxy S7 Edge的Android7.0系统无法正常显示出悬浮框

### ISSUE THREAD

**Issue by smuwjs** [zhaozepeng/FloatWindowPermission#32]

**Comment by smuwjs** [comment]
还有Nexus6的Android7.1.1系统权限判断方式也有问题

**Comment by zhaozepeng** [comment]
Android 6.0 之后的判断方式就是使用系统提供的API了，具体是什么问题呢？

**Comment by smuwjs** [comment]
![image](https://user-images.githubusercontent.com/12137473/37385793-a96dc112-2790-11e8-80d3-014eef4923a7.png)
通知全部屏蔽，返回的权限还是true。

**Comment by smuwjs** [comment]
这是Nexus6的机型，Android7.1.1原生的。

**Comment by zhaozepeng** [comment]
@smuwjs 通知栏？悬浮窗权限是在其他应用之上显示

**Comment by smuwjs** [comment]
@zhaozepeng Sorry，我需要检测的权限是这个通知栏权限，可能跟这个悬浮窗权限不一样，谢谢你的提醒。

**Comment by LiuLei0571** [comment]
可以看下我的github上面的资料，前段时间专门针对这个弹窗问题做了调研，测试IDE机型涵盖了市面上绝大部分的手机与系统API
